### ISSUE TITLE
Export .csv Tickets Z

### ISSUE THREAD

**Issue by cedricreynier** [ScilCoop/pasteque-server#11]
Bonjour

J'ai un problème sur l'export du ticket Z depuis l'interface de gestion.
Le .csv ne fait pas apparaitre les montants en espèce, carte bleu etc. alors qu'ils apparaissent sur l'interface. (bug recopié depuis le forum)

**Comment by philippepary** [comment]
Bug connu. Son origine reste mystérieuse malgré bien des recherches

**Comment by philippepary** [comment]
issue related to strtoupper() in PHP
