### ISSUE TITLE
Pasteque modifies ticket when prepaid account is updated

### ISSUE THREAD

**Issue by cedricreynier** [ScilCoop/pasteque-server#14]
When opening a new ticket in pasteque desktop to update customer account, it works fine. But, when this ticket is closed, the last ticket appears with modified values (ie 0,258kg of pain aux olives is set at 0xpain aux olives. It seems that there is an automatic rounding.
It is very annoying because we sell many products by weight, so we have to re weigh all the products. 

Thanks in advance

**Comment by philippepary** [comment]
This bug should be declared in Pasteque-Desktop

**Comment by philippepary** [comment]
This was realy a Pasteque-Server bug on database scheme
