### ISSUE TITLE
Use of Open Food Facts data.

### ISSUE THREAD

**Issue by teolemon** [ScilCoop/pasteque-server#6]
You might want to use Open Food Facts data for products:
http://world.openfoodfacts.org

A nice bonus would be to let users of Pastèque contribute to the database for their products that are not complete.

**Comment by philippepary** [comment]
How would you see that kind of integration ? A module for resquesting OpenFoodFacts that auto-create products ?

**Comment by teolemon** [comment]
I was thinking of:
- a module to let Pasteque POS consume Open Food Facts data (send a barcode, get detailed info about the scanned product that could be used for various purposes)
- a module that would let Pasteque users add missing products to Open Food Facts, so that over time, less input and reliance on closed DBs is required.

**Comment by philippepary** [comment]
Hum, where in Pastèque ? We are sometimes talking about an « notes » fields for product, but currently have nothing. So, it’s a good idea but who will do it ? :)

**Comment by philippepary** [comment]
Pastèque has many other things to do. Won’t get done until a while
